/**
 * Build the token outputs from one DTCG source.
 *
 *   tokens/**.json  (DTCG, the only source of truth)
 *        │
 *        ├─→ src/generated/tokens.ts          consumed by StyleSheet
 *        ├─→ src/generated/tailwind-preset.ts consumed by Tailwind / NativeWind
 *        └─→ assets/variables.css             consumed by the web catalog
 *
 * Style Dictionary resolves the aliases; the emitters below are deliberately
 * small so the shape of the output stays obvious.
 */
import { mkdir } from 'node:fs/promises'
import StyleDictionary from 'style-dictionary'

const HEADER = `// Generated by build.mjs from tokens/**.json — do not edit by hand.\n`

/** Walk the resolved token tree and return plain nested values. */
function plain(node) {
  if (node && typeof node === 'object' && '$value' in node) return node.$value
  if (node && typeof node === 'object') {
    const out = {}
    for (const [k, v] of Object.entries(node)) {
      if (k.startsWith('$')) continue
      out[k] = plain(v)
    }
    return out
  }
  return node
}

/** Numeric tokens are more useful to React Native as numbers. */
function unpx(value) {
  if (typeof value === 'string' && /^-?\d+(\.\d+)?px$/.test(value)) return Number.parseFloat(value)
  return value
}

function deepMap(value, fn) {
  if (value && typeof value === 'object') {
    const out = Array.isArray(value) ? [] : {}
    for (const [k, v] of Object.entries(value)) out[k] = deepMap(v, fn)
    return out
  }
  return fn(value)
}

function tsLiteral(value, indent = 0) {
  const pad = '  '.repeat(indent)
  if (value && typeof value === 'object') {
    const body = Object.entries(value)
      .map(([k, v]) => `${pad}  ${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${tsLiteral(v, indent + 1)},`)
      .join('\n')
    return `{\n${body}\n${pad}}`
  }
  return JSON.stringify(value)
}

StyleDictionary.registerFormat({
  name: 'np/ts-tokens',
  format({ dictionary }) {
    const all = deepMap(plain(dictionary.tokens), unpx)
    const { color, space, radiusStep, spacing, radius, iconSize, scheme, control } = all
    return [
      HEADER,
      `export const primitive = ${tsLiteral({ color, space, radiusStep })} as const\n`,
      `export const spacing = ${tsLiteral(spacing)} as const\n`,
      `export const radius = ${tsLiteral(radius)} as const\n`,
      `export const iconSize = ${tsLiteral(iconSize)} as const\n`,
      `export const scheme = ${tsLiteral(scheme)} as const\n`,
      `export const control = ${tsLiteral(control)} as const\n`,
    ].join('\n')
  },
})

StyleDictionary.registerFormat({
  name: 'np/tailwind-preset',
  format({ dictionary }) {
    const all = deepMap(plain(dictionary.tokens), unpx)
    const px = (o) => Object.fromEntries(Object.entries(o).map(([k, v]) => [k, typeof v === 'number' ? `${v}px` : v]))
    const preset = {
      theme: {
        extend: {
          colors: { ...all.color, ...all.scheme.light },
          spacing: px(all.spacing),
          borderRadius: px(all.radius),
        },
      },
    }
    return `${HEADER}\nconst preset = ${tsLiteral(preset)} as const\n\nexport default preset\n`
  },
})

StyleDictionary.registerFormat({
  name: 'np/css-variables',
  format({ dictionary }) {
    const all = deepMap(plain(dictionary.tokens), unpx)
    const lines = (obj, prefix) =>
      Object.entries(obj).flatMap(([k, v]) =>
        v && typeof v === 'object'
          ? lines(v, `${prefix}-${k}`)
          : [`  --${prefix}-${k}: ${typeof v === 'number' ? `${v}px` : v};`],
      )
    return [
      '/* Generated by build.mjs from tokens/**.json — do not edit by hand. */',
      ':root {',
      ...lines(all.spacing, 'spacing'),
      ...lines(all.radius, 'radius'),
      ...lines(all.scheme.light, 'color'),
      '}',
      '',
      ':root[data-theme="dark"] {',
      ...lines(all.scheme.dark, 'color'),
      '}',
      '',
    ].join('\n')
  },
})

await mkdir('src/generated', { recursive: true })
await mkdir('assets', { recursive: true })

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  usesDtcg: true,
  log: { verbosity: 'silent' },
  platforms: {
    ts: {
      transformGroup: 'js',
      buildPath: 'src/generated/',
      files: [
        { destination: 'tokens.ts', format: 'np/ts-tokens' },
        { destination: 'tailwind-preset.ts', format: 'np/tailwind-preset' },
      ],
    },
    css: {
      transformGroup: 'css',
      buildPath: 'assets/',
      files: [{ destination: 'variables.css', format: 'np/css-variables' }],
    },
  },
})

await sd.buildAllPlatforms()

console.log('tokens: built')
